#!/bin/bash
# Author: Mark Muench
# Date: 10/18/2024
# Version: 1.0
# Description:  This file acts as a tester- it will run
#               multiple instances of main with several
#               different parameters.

# Note: usage is: ./myprogram <num producers> <num consumer> <numItems> <cacheSize> <delay>

# Start of tester:   

echo "Running Tests...\n"


# File you want to check
FILE="myprogram"

# Check if the file exists
if [ -f "$FILE" ]; then
    echo "$FILE exists."
else
    echo "$FILE does not exist. Compiling the program..."
    make clean
    make
    echo "\n\n"
fi

## Tests
echo "Test 1: Default myprog"
./myprogram

echo "Test 2: 1p, 1c, 10 itm, 5 cache"
./myprogram -p 1 -c 1 -i 10 -s 5 

echo "Test 3: Test 2 with delay 3"
./myprogram -p 1 -c 1 -i 10 -s 5 -d 3


echo "Test 4: 5p 5c 10 itm, 8 cache"
./myprogram -p 5 -c 5 -i 10 -s 8 


echo "Test 5: Test 4 but with del 1"
./myprogram -p 5 -c 5 -i 10 -s 8 -d 1

echo "=== EDGE CASES: ==="
./myprogram -p 1 -c 1 -i 100 -s 1
./myprogram -p 50 -c 1 -i 10 -s 5

echo "\n\n"